#!/usr/bin/perl
# ---   *   ---   *   ---
# CHARTAB
# makes lycon char table

# LIBRE SOFTWARE
# Licensed under GNU GPL3
# be a bro and inherit

# CONTRIBUTORS
# lyeb,
# ---   *   ---   *   ---

# deps
  use v5.36.0;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/lib/';

  use Emit::Std;
  use Emit::C;

# ---   *   ---   *   ---
# info

  our $VERSION=v0.00.2;
  our $AUTHOR='IBN-3DILA';

# ---   *   ---   *   ---

sub generator($fname) {

  print {*STDERR} "$fname\n";

  my $s="wchar_t chartab[]=\n  ";

  for(my $i=0;$i<256;$i++) {

    my $c=($i<0x20 || $i>0x7F)
      ? $i+0x100
      : $i
      ;

    my $h=sprintf "%04X",$c;

    if(!($i%4)) {
      if($i) {$s.="\"\n  "};
      $s.='L"';

    };

    $s.="\\x$h";

  };

# ---   *   ---   *   ---

  return $s.q{"};

};

# ---   *   ---   *   ---

#my $root=shb7::root $ENV{'ARPATH'};
#chdir $root;

Emit::Std::outf(

  'C','ce/chartab.h',

  body=>\&generator,
  args=>[],

  add_guards=>1,

);

# ---   *   ---   *   ---
1; # ret
