#!/usr/bin/perl
#
# Tests drawing classes
#
# ---   *   ---   *   ---

# deps
  use v5.36.0;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/ce/';
  use Vec4;
  use Line;
  use Rect;

# ---   *   ---   *   ---

my $rect=Rect->nit('30x30',40);

$rect->draw();
$rect->textfit(q{Hello there!}x64);

# ---   *   ---   *   ---
1; # ret
