#!/usr/bin/perl
#
# Tests drawing classes
#
# ---   *   ---   *   ---

# deps
  use v5.36.0;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/lib/';

  use Lycon;
  use GF::Mode::ANSI;

  use GF::Rect;

# ---   *   ---   *   ---

my @ttysz=(0,0);Lycon::ttysz(\@ttysz);

my $G=GF::Mode::ANSI->new_frame();
$G->nit(0,@ttysz);

# ---   *   ---   *   ---

my $rect=GF::Rect->nit('20x30',pos_x=>30);

my @lines=$rect->textfit(
  [q{Hello there!}x64]

);

$rect->text_update(\@lines);

print "\e[2J";

$G->{-buff}.=join q{},@lines;
$G->draw();

# ---   *   ---   *   ---
1; # ret
