#!/usr/bin/perl
#
# Tests drawing classes
#
# ---   *   ---   *   ---

# deps
  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);
  use lib $ENV{'ARPATH'}.'/lib/';

  use Lycon;

  use GF::Mode::ANSI;

  use GF::Vec4;
  use GF::Icon;
  use GF::Line;
  use GF::Rect;

# ---   *   ---   *   ---

my $G   = GF::Mode::ANSI->canvas();
my @out = ();

# ---   *   ---   *   ---

#my $vec=GF::Vec4->nit(0,0);
#push @out,$vec->sput(char=>$GF::Icon::PAIN_DED);

# ---   *   ---   *   ---

#my $line=GF::Line->nit([0,0],[0,3]);
#push @out,$line->sput(char=>q[\\]);

## ---   *   ---   *   ---

#my $rect=GF::Rect->nit('20x9',pos_x=>4,e_char=>q[*],border=>1);
#
#$rect->textfit(
#  [q(),q(Hello there, stranger! I shall be your guide through these darklands...)]
#
#);
#
#push @out,$rect->sput();

# ---   *   ---   *   ---

$G->req(@out);
$G->draw();

# ---   *   ---   *   ---
1; # ret
