#!/usr/bin/perl
#
# finally!
#
# ---   *   ---   *   ---

# deps
package main;
  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/ce/';

  use Rect;

  use lib $ENV{'ARPATH'}.'/lib/sys/';
  use lib $ENV{'ARPATH'}.'/lib/';

  use Style;
  use Arstd::String;
  use Arstd::IO;

  use Lycon;

  use Lycon::Clk;
  use Lycon::Ctl;
  use Lycon::Dpy;
  use Lycon::Kbd;
  use Lycon::Loop;

  use Graphics::ANSI;

  binmode(STDOUT,':utf8');

# ---   *   ---   *   ---

my $Cache={

  terminate=>0,

};

my $Update_Screen=1;
my $Update_Cursor=0;

my $Scroll_Y=0;
my $Y_Offset=0;

# ---   *   ---   *   ---

my @ttysz=(0,0);
Lycon::ttysz(\@ttysz);

my $G=Lycon::Loop::graphics('ANSI');
$G->nit($ttysz[0],$ttysz[1],0);

my $Canvas=$G->{-canvas};
my $Cursor=$G->{-cursor};

# ---   *   ---   *   ---

my $File=orc('./avto');

my @File_Lines=split $NEWLINE_RE,$File;

@File_Lines=$Canvas->textfit(
  \@File_Lines,
  offscreen=>1,

);

my @Screen_Lines=();

sub on_scroll() {

  $Y_Offset+=$Scroll_Y;
  $Y_Offset*=0+(($Y_Offset>=0));

  my $beg=$Y_Offset;
  my $end=$Y_Offset+$Canvas->{sz_y}-1;

  for my $x($beg,$end) {
    if($x>$#File_Lines) {$x=$#File_Lines};

  };

  @Screen_Lines=@File_Lines[$beg..$end];
  if(@Screen_Lines<$Canvas->{sz_y}) {
    my $diff=$Canvas->{sz_y}-@Screen_Lines;
    push @Screen_Lines,($NULLSTR) x $diff;

  };

  my $i=1;map {

    $ARG=

    q[$:gd_mvcur ].$i.q[,1;>].
    q[$:gd_cline;>].

      "$ARG";

    $i++;

  } @Screen_Lines;

  $Scroll_Y=0;

};

on_scroll();

# ---   *   ---   *   ---

my $Curline_Original=$NULLSTR;

sub highlight_current() {

  my $curline=$Cursor->[1];
  $curline=$#Screen_Lines if $curline>$#Screen_Lines;

  $Curline_Original=$Screen_Lines[$curline];

  my $diff=

    (length $Curline_Original)
  - length Peso::Ipret::depesc($Curline_Original)

  ;

  my $sz=$Canvas->{sz_x}+$diff;

  $Screen_Lines[$curline]=

    q[$:gd_color 0x87;>].

    (

    sprintf "%-${sz}s",
      $Screen_Lines[$curline]

    ).

    q[$:gd_color 0x07;>]

  ;

};

sub restore_current() {

  my $curline=$Cursor->[1];
  $curline=$#Screen_Lines if $curline>$#Screen_Lines;

  $Screen_Lines[$curline]=$Curline_Original;

};

# ---   *   ---   *   ---

sub cursor_up() {
  $Scroll_Y-=$Cursor->[1]==0;
  $Cursor->[1]-=$Cursor->[1]>0;

  $Update_Cursor=1;

};

sub cursor_down() {
  $Scroll_Y+=$Cursor->[1]>=$Canvas->{sz_y}-2;
  $Cursor->[1]+=$Cursor->[1]<$Canvas->{sz_y}-2;

  $Update_Cursor=1;

};

sub cursor_left() {
  $Cursor->[0]-=$Cursor->[0]>0;
  $Update_Cursor=1;

};

sub cursor_right() {
  $Cursor->[0]+=$Cursor->[0]<$Canvas->{sz_x};
  $Update_Cursor=1;

};

# ---   *   ---   *   ---

Lycon::Ctl::register_events(

  -COM=>[

    # escape
    0,0,sub {$Cache->{terminate}=1},

    # ret
    0,0,0,

    #space
    0,0,0,

  ],

  -CTL_L=>[

    # shift
    0,0,0,

    # ctrl
    0,0,0,

    # alt
    0,0,0,

  ],

  -MOV_A=>[

    # up
    \&cursor_up,\&cursor_up,0,

    # left
    \&cursor_left,\&cursor_left,0,

    # down
    \&cursor_down,\&cursor_down,0,

    # right
    \&cursor_right,\&cursor_right,0,

  ],

);

# ---   *   ---   *   ---

Lycon::Kbd::nit();
Lycon::Loop::set_quit(sub {

  return $Cache->{terminate};

});

Lycon::Clk::nit();

# ---   *   ---   *   ---

Lycon::Loop::set_logic(sub {

  $Update_Screen|=($Scroll_Y!=0) || $Update_Cursor;

  on_scroll() if $Scroll_Y;

  my $screen=$NULLSTR;
  if($Update_Screen) {
    highlight_current();

    $screen=join $NULLSTR,@Screen_Lines;

    restore_current();

  };

# ---   *   ---   *   ---

my $ibuff=Lycon::keyibl();

  Lycon::Loop::dwbuff(

    q[$:gd_encur 0;>].

    $ibuff.

    q[$:gd_mvcur

      $O{gd}->{-canvas}->{sz_y}+1,1

    ;>].

    q[$:gd_cline;>].
    q[$:gd_color 0x70;>].

    # status bar
    (sprintf

      "%lc %i/%i %i",

      Lycon::clkdr(),

      $Cursor->[1],
      $Canvas->{sz_y},$Y_Offset,

    ).

    q[$:gd_color 0x07;>].

    # cursor
    q[$:gd_mvcur

      $O{gd}->{-cursor}->[1]+1,
      $O{gd}->{-cursor}->[0]+1,

    ;>].

    q[$:gd_encur 1;>]

  );

  $Update_Screen=0;

},[]);

# ---   *   ---   *   ---

Lycon::Kbd::swap_to();

Lycon::Dpy::beg();
Lycon::Loop::run(panic=>6000);
Lycon::Dpy::end();

# ---   *   ---   *   ---
1; # ret
