#!/usr/bin/perl
#
# Tests the Lycon controllers

# ---   *   ---   *   ---
# deps

package main;

  use v5.36.0;
  use strict;
  use warnings;

  use lib $ENV{'ARPATH'}.'/lib/sys/';
  use lib $ENV{'ARPATH'}.'/lib/';

  use Style;

  use Lycon::Ctl;
  use Lycon::Loop;

# ---   *   ---   *   ---

my $Cache={

  terminate=>0,
  init=>0,

};

# ---   *   ---   *   ---

Lycon::Ctl::register_events(

  escape=>[0,0,sub {
    $Cache->{terminate}=1;

  }],

);

my $main=defmain(

  quit     => sub {
    return $Cache->{terminate};

  },

  logic    => {
    args=>[],
    proc=>sub () {}

  },

  graphics => 'ANSI',
  clock    => {},

);


$main->();

# ---   *   ---   *   ---
1; # ret
